name: Custom Actions demos

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Custom action in the same repository ğŸ‘‡ğŸ»ğŸ“¦
      id: hello
      uses: ./custom-action
      with:
        who-to-greet: "Gisela Torres"
    
    - name: Check the output ğŸ“º
      run: echo "The time was ${{ steps.hello.outputs.time }}"