name: GitHub-hosted runners
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  ubuntu-job:    
    runs-on: ubuntu-latest
    steps:
    - run: |
        os_version=$(cat /etc/os-release)
        echo "ðŸŽ‰ This job uses Ubuntu $os_version"
  windows-job:    
    runs-on: windows-latest
    steps:
    - run:
        $WIN_VERSION=$(systeminfo | findstr /B /C:"OS Name" /B /C:"OS Version")
        echo "ðŸŽ‰ This job uses Windows $WIN_VERSION"
  macos-job:    
    runs-on: macos-latest
    steps:
    - run: |
        sw_version=$(sw_vers)
        echo "ðŸŽ‰ This job uses MacOs\n$sw_version"
