name: Reusable workflow example # https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:
  workflow_call:
    inputs:
      greeting:
        description: 'A friendly greeting'
        type: string
        required: true
        default: 'Hello'
    secrets:
      MY_SECRET:
        description: 'A secret value'
        required: true

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - name: See inputs and secrets
      run: |
        echo "The greeting was ${{ inputs.greeting }}"
        echo "The secret was ${{ secrets.MY_SECRET }}"
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        dotnet restore        
    - name: Build
      run: |
        dotnet build --no-restore