name: Secrets

on:
  workflow_dispatch:

env:
  CHECK_SECRET: ${{ secrets.CHECK_SECRET}}

jobs:
  testing_secrets:
    name: Testing secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: My first secret
        run: echo ${{ secrets.MY_SECRET }}
      - name: My org secret
        run: echo ${{ secrets.SECRET_FOR_ORG }} 
      - name: If a secret with the same name exists at multiple levels, the secret at the lowest level takes precedence
        run: echo ${{ secrets.REUSED_SECRET_NAME }} 
      - name: Check secret
        if: env.CHECK_SECRET == 'true'
        run: echo "The secret has false value"
      - name: Decrypt a secret using a secret
        run: |
          mkdir -p $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.LARGE_SECRET_PASSPHRASE }}" \
            --output $HOME/secrets/larger_secret.txt secret.txt.gpg
          cat $HOME/secrets/larger_secret.txt